// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaspredeleniyeDutyaApp.Data;

#nullable disable

namespace RaspredeleniyeDutyaApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250725113412_InitialDataRenamed")]
    partial class InitialDataRenamed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaspredeleniyeDutyaApp.Data.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("RaspredeleniyeDutyaApp.Data.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Data", "RaspredeleniyeDutyaApp.Data.Variant.Data#InitialData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("DavlDut")
                                .HasColumnType("double precision");

                            b1.Property<double>("DiamFurm")
                                .HasColumnType("double precision");

                            b1.PrimitiveCollection<List<bool>>("FurmPodachaDutya")
                                .IsRequired()
                                .HasColumnType("boolean[]");

                            b1.Property<double>("GornDiam")
                                .HasColumnType("double precision");

                            b1.Property<double>("HeightFurm")
                                .HasColumnType("double precision");

                            b1.Property<double>("KoefSzhatOchag")
                                .HasColumnType("double precision");

                            b1.Property<int>("NRabFurm")
                                .HasColumnType("integer");

                            b1.Property<double>("RashDut")
                                .HasColumnType("double precision");

                            b1.PrimitiveCollection<List<double>>("RashGazNaF")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.PrimitiveCollection<List<double>>("RashVodiNaF")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.Property<double>("SodKislorod")
                                .HasColumnType("double precision");

                            b1.Property<double>("TDut")
                                .HasColumnType("double precision");

                            b1.PrimitiveCollection<List<double>>("TPerepad")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.Property<double>("TrebZnTeor")
                                .HasColumnType("double precision");

                            b1.Property<double>("VlazDut")
                                .HasColumnType("double precision");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("RaspredeleniyeDutyaApp.Data.Variant", b =>
                {
                    b.HasOne("RaspredeleniyeDutyaApp.Data.UserAccount", "Owner")
                        .WithMany("Variants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RaspredeleniyeDutyaApp.Data.UserAccount", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
